spring.application.name=cursos-service
server.port=8082

# Configuracion Oracle Cloud
spring.datasource.url=jdbc:oracle:thin:@plataformaeducativa_tp?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Oraclecloud123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

oracle.jdbc.fanEnabled=false

# Azure AD - CAMBIAR por los valores de tu App Registration nueva (mismos que el BFF)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://CAMBIAR.b2clogin.com/CAMBIAR-tenant-id/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://CAMBIAR.b2clogin.com/CAMBIAR.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi

# RabbitMQ (debe apuntar al mismo contenedor rabbitmq que usa el BFF)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
