spring.application.name=bff-inscripciones
server.port=8081

# AWS S3
aws.region=us-east-1
aws.s3.bucket=plataforma-educativa-duoc-CAMBIAR

# Carpeta temporal local donde se genera el PDF antes de subirlo a S3
resumenes.temp.path=/app/temp

# Azure AD - CAMBIAR por los valores de tu App Registration nueva
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://CAMBIAR.b2clogin.com/CAMBIAR-tenant-id/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://CAMBIAR.b2clogin.com/CAMBIAR.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
